[package]
name = "qt-cargo"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cc = { version = "1.0", features = ["parallel"] }
walkdir = "2.0"
pathdiff = "0.2"
tempdir = "*"
