[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "qt-cargo"
version = "0.1.0"

[dependencies]
boyer-moore-magiclen = "0.2"
pathdiff = "0.2"
tempdir = "*"
walkdir = "2.0"
itertools = "0.9"
num_cpus = "0.2"

[dependencies.cc]
features = ["parallel"]
version = "1.0"
