// This file contains source file lists for Qt components. When kept
// in a central location they can also be used by the auto-tests in
// lib.rs, in addition to by build.rs scripts.

pub const BOOTSTRAP_PATH: &'static str = "qtbase/src/corelib";
pub const BOOTSTRAP_SOURCES: &'static [&'static str] = &[
    "global/qendian.cpp",
    "global/qfloat16.cpp",
    "global/qglobal.cpp",
    "global/qlogging.cpp",
    "global/qmalloc.cpp",
    "global/qnumeric.cpp",
    "global/qoperatingsystemversion.cpp",
    "global/qrandom.cpp",
    "io/qabstractfileengine.cpp",
    "io/qbuffer.cpp",
    "io/qdebug.cpp",
    "io/qdir.cpp",
    "io/qdiriterator.cpp",
    "io/qfile.cpp",
    "io/qfiledevice.cpp",
    "io/qfileinfo.cpp",
    "io/qfilesystemengine.cpp",
    "io/qfilesystementry.cpp",
    "io/qfsfileengine.cpp",
    "io/qfsfileengine_iterator.cpp",
    "io/qiodevice.cpp",
    "io/qipaddress.cpp",
    "io/qloggingcategory.cpp",
    "io/qloggingregistry.cpp",
    "io/qresource.cpp",
    "io/qsavefile.cpp",
    "io/qstandardpaths.cpp",
    "io/qtemporarydir.cpp",
    "io/qtemporaryfile.cpp",
    "io/qurl.cpp",
    "io/qurlidna.cpp",
    "io/qurlquery.cpp",
    "io/qurlrecode.cpp",
    "kernel/qcoreapplication.cpp",
    "kernel/qcoreglobaldata.cpp",
    "kernel/qiterable.cpp",
    "kernel/qmetacontainer.cpp",
    "kernel/qmetatype.cpp",
    "kernel/qsharedmemory.cpp",
    "kernel/qsystemerror.cpp",
    "kernel/qsystemsemaphore.cpp",
    "kernel/qvariant.cpp",
    "plugin/quuid.cpp",
    "serialization/qcborcommon.cpp",
    "serialization/qcborstreamwriter.cpp",
    "serialization/qcborvalue.cpp",
    "serialization/qdatastream.cpp",
    "serialization/qjsonarray.cpp",
    "serialization/qjsoncbor.cpp",
    "serialization/qjsondocument.cpp",
    "serialization/qjsonobject.cpp",
    "serialization/qjsonparser.cpp",
    "serialization/qjsonvalue.cpp",
    "serialization/qjsonwriter.cpp",
    "serialization/qtextstream.cpp",
    "serialization/qxmlstream.cpp",
    "serialization/qxmlstreamgrammar.cpp",
    "serialization/qxmlutils.cpp",
    "text/qbytearray.cpp",
    "text/qbytearraylist.cpp",
    "text/qbytearraymatcher.cpp",
    "text/qlocale.cpp",
    "text/qlocale_tools.cpp",
    "text/qregularexpression.cpp",
    "text/qstring.cpp",
    "text/qstringbuilder.cpp",
    "text/qstringconverter.cpp",
    "text/qstringlist.cpp",
    "text/qvsnprintf.cpp",
    "time/qcalendar.cpp",
    "time/qdatetime.cpp",
    "time/qgregoriancalendar.cpp",
    "time/qromancalendar.cpp",
    "tools/qarraydata.cpp",
    "tools/qbitarray.cpp",
    "tools/qcommandlineoption.cpp",
    "tools/qcommandlineparser.cpp",
    "tools/qcryptographichash.cpp",
    "tools/qhash.cpp",
    "tools/qline.cpp",
    "tools/qpoint.cpp",
    "tools/qrect.cpp",
    "tools/qringbuffer.cpp",
    "tools/qsize.cpp",
    "tools/qversionnumber.cpp",
];

pub const BOOTSTRAP_SOURCES_UNIX: &'static [&'static str] = &[
    "io/qfilesystemengine_unix.cpp",
    "io/qfilesystemiterator_unix.cpp",
    "io/qfsfileengine_unix.cpp",
    "kernel/qcore_unix.cpp",
    "kernel/qsharedmemory_posix.cpp",
    "kernel/qsharedmemory_systemv.cpp",
    "kernel/qsharedmemory_unix.cpp",
    "kernel/qsystemsemaphore_posix.cpp",
    "kernel/qsystemsemaphore_systemv.cpp",
    "kernel/qsystemsemaphore_unix.cpp",
];

pub const MOC_PATH: &'static str = "qtbase/src/tools/moc";
pub const MOC_SOURCES: &'static [&'static str] = &[
    "collectjson.cpp",
    "generator.cpp",
    "main.cpp",
    "moc.cpp",
    "parser.cpp",
    "preprocessor.cpp",
    "token.cpp",
];
